### ISSUE TITLE
执信初二五同学求罩

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#1]
我是执信初二五班的同学，请问你们的整个项目都是团委开发的？
我也是研究php的，请问能不能加上我。嘻嘻~
我自己也有一个项目哦~欢迎来看看

**Comment by zhangjingye03** [comment]
(⊙o⊙)哇，少见的同行哎 :joy: 欢迎欢迎，我也想虚心学习学习学弟的风范，初二的时候我还在玩vb.net呢 :joy: 

准确来说，除了介绍中声明的框架外，其他代码是我一个人写的(那帮人有点懒...其实我也很懒，这么点代码拖了一个多学期)

学生会也有他们的[项目](https://github.com/zhxsuwebgroup/SUsage) (没搞好，目前完全没做后端)，你也可以去看看

**Comment by Linzecong** [comment]
执信果然人才辈出~！！！

**Comment by SmallOyster** [comment]
学长是学生会的吧(手动偷笑)。
请问你你们的项目的网址是多少啊？

**Comment by zhangjingye03** [comment]
人家可是上上届的团委信息部部长... :joy:

**Comment by SmallOyster** [comment]
😂😂学长毕业了还来看哈哈哈。学长好！

**Comment by Linzecong** [comment]
真是厉害呀~~信息部好啊，以后来信息部~！

**Comment by SmallOyster** [comment]
我才初二还没入团……我也好想入团加入信息部啊
