### ISSUE TITLE
success.php 关闭窗口button无效

### ISSUE THREAD

**Issue by nenekodev** [zhxtw/qingzhi#10]
隔壁前来测试。
现发现有几率产生点击关闭btn无效状况。

**Comment by SmallOyster** [comment]
什么意思？能不能附上一张图片？
以便我们修复Bug(๑•̀ω•́๑)
谢谢配合！

> Project Assist Developer
> Jerry Cheung

**Comment by SmallOyster** [comment]
另外有种可能是您未完全加载完所有css/js而导致的。

> Project Assist Developer
> Jerry Cheung

**Comment by nenekodev** [comment]
好的，由于已经提交了志愿者申请，不便再次进入success页面截图，同时建议你们review一下此页面下方的“关闭窗口”按钮，个人建议是不如取消此按钮，只保留返回主页按钮，减少功能重复提高可靠性。

**Comment by zhangjingye03** [comment]
谢谢反馈
之前我也留意到了这个bug，感觉没什么用就没鸟

然而，一个人做压力很大(我tm真想喷另外两个懒鬼)，从webui美观到服务器安全都要符合条件，整个系统完全做好再go live会花费巨大的时间和精力(你要是看看我之前的commits，其实陆陆续续拖了一个学期了，只是周末写代码，考试那几个星期基本没动)；所以只能这样边做边debug咯，顺便督促督促自己

@yyl99311 咳咳，说到强行go live我又想起了ttk....那个页面无法滚动的创意真好 :joy:

**Comment by nenekodev** [comment]
收到

**Comment by zhangjingye03** [comment]
已修复，等再完善几个小功能就push到服务器上
再次感谢 :+1:
