### ISSUE TITLE
在Github项目库中如何新建文件夹？

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#14]
在Github项目库中如何新建文件夹？

**Comment by zhangjingye03** [comment]
你用什么方式commit上来的

**Comment by SmallOyster** [comment]
就普通网页版啊。我不会用Git……

**Comment by zhangjingye03** [comment]
你试试整个文件夹拖进网页

**Comment by zhangjingye03** [comment]
或者用github for windows的客户端

**Comment by SmallOyster** [comment]
不会用客户端……安装后就是一个cmd……

**Comment by SmallOyster** [comment]
客户端不是应该有面板的吗？为啥只有一个cmd

**Comment by zhangjingye03** [comment]
- 可以直接建立文件夹，然后再`git commit && git push`
- Github有windows客户端的图形界面，[详见](https://desktop.github.com/)

**Comment by SmallOyster** [comment]
你用的三个git桌面版还是git dash？
