### ISSUE TITLE
更新日志 && 日后目标

### ISSUE THREAD

**Issue by zhangjingye03** [zhxtw/qingzhi#15]
- [x] 修复导出excel的小bug  https://github.com/zhxtw/qingzhi/commit/bd200445250ca36d338ce51edb62fa2915cb2099
- [x] 增加底部版本信息显示 https://github.com/zhxtw/qingzhi/commit/33d579abfd5a16285825ca7a3307a1c0ce311541
- [x] 修复#21 https://github.com/zhxtw/qingzhi/commit/470a749c5cf8888492372e673ff172a77dec815c
- [x] 修复#25 以及其他地方复现的bug https://github.com/zhxtw/qingzhi/commit/04d9f175bfc3252db93ce6a247d7ab08953c83d8
- [x] 做完管理地点 https://github.com/zhxtw/qingzhi/commit/5433864fe0edb4ae6f9983649a4dd48e8a4ab387
- [x] 更新验证码框架为github上较安全的框架 https://github.com/zhxtw/qingzhi/commit/a475c0df92002e989dded71637f46d5a6002fc0e
- [x] 后台分配时间，耗时预计一星期 https://github.com/zhxtw/qingzhi/commit/971b11a32130ff72583f96609ca61a7df0d79573
- [x] 自己写一份较安全的query前过滤函数，争取使用PDO以兼容跨平台 https://github.com/zhxtw/qingzhi/commit/fb2efc107c9515bfce60a975e2760ed222c0bcb1
- [ ] ~~前后台瀑布流样式(否则地点简介多一行下面的就被空出来了)，`float`无果，`-webkit-column-count:3`和`-webkit-column-break-inside:avoid`太麻烦要考虑media query而且有阴影溢出的bug（ **调整`box-shadow`即可**），若`overflow:hidden`又没有边框恶心至极。。。。有空考虑下[bootstrap-waterfall](https://github.com/Mystist/bootstrap-waterfall/)~~ **暂时懒得做**
- [x] 后台界面美化https://github.com/zhxtw/qingzhi/commit/ea35dba37083ee64f827b2d5bfb2705787e41a5c https://github.com/zhxtw/qingzhi/commit/50fca3883bbcd7b6f324456ff7a81110c980cea5
- [x] 时间分配的判断和自动分配时间 (初步支持@https://github.com/zhxtw/qingzhi/commit/b4e254c2fdba5f4e6a94ebf83a0e5e81578a54b2 https://github.com/zhxtw/qingzhi/commit/22b657d9a9245964fd0b5bb139805445b7e81f7b 基本完成@https://github.com/zhxtw/qingzhi/commit/c5256c97d6fadf3871617d1356ba8e9e35ae6b7d https://github.com/zhxtw/qingzhi/commit/b3c7e56d912273307d7513d6285dee94f2ddb186)
- [ ] 前后台文件太多太乱，理应归顺到对应功能的文件夹中
- [ ] 网站全局设置json，读+写 (初步支持@https://github.com/zhxtw/qingzhi/commit/4fcd8bbb0be595fa778cc1c74d1e231791bb8270)
- [ ] 志愿者展示和工时统计
- [x] 前端页面的资源优化以加快访问速度
- [x] 后台登录界面美化 https://github.com/zhxtw/qingzhi/commit/5d1dcf3869467890deac86a10620019648af2318
- [x] 完成迁移tableutils、mktable等后台table的相关函数 https://github.com/zhxtw/qingzhi/commit/79006cb549cdae4189e70448230c7b030bc6678c
- [ ] 看看#33，可能需要新建branch

**Comment by JerryLoveZhiXin** [comment]
我给你开的feedback还没接收…………
如果我搞完我爸的要不要我来帮你？

**Comment by kongoldwant** [comment]
楼主，请问一下这个志愿者的系统有数据库文件吗

**Comment by zhangjingye03** [comment]
@JerryLoveZhiXin  已经接受，需要增加安全性才能投入使用
@kongoldwant 有，刚添加初始数据库文件，详见 [此处](https://github.com/zhxtw/qingzhi/blob/6daf01e30e9a095f9846515a995a68666da515cb/initial.sql)

**Comment by kongoldwant** [comment]
学长，我再导入初始数据库文件时发生了错误，能帮忙看一下吗 Mysql5.1
执行的SQL语句出错：
CREATE TABLE IF NOT EXISTS `userpwd` (
  `id` int(11) NOT NULL,
  `certName` varchar(1024) NOT NULL,
  `certSerial` varchar(32) NOT NULL,
  `username` varchar(20) NOT NULL,
  `pwd` varchar(32) NOT NULL,
  `salt` varchar(5) NOT NULL,
  `img` varchar(128) NOT NULL,
  `datetime`  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8
错误信息：You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB ' at line 9

**Comment by kongoldwant** [comment]
学长，我再导入您的初始数据库文件时出现了错误 mysql5.1
执行的SQL语句出错：
ALTER TABLE `auto_time`
  ADD PRIMARY KEY (`id`)
错误信息：Multiple primary key defined

**Comment by JerryLoveZhiXin** [comment]
@kongoldwant 错误内容是您的SQL版本过低，请升级。
我们这个文件，SQL应该是要5.5吧？

> Project Assist Developer
> Jerry Cheung

**Comment by JerryLoveZhiXin** [comment]
@kongoldwant 
如果有问题欢迎向我们提问哦~

## 小小建议
每个问题开一个issues。谢谢！

> ZHXTW Website Assist Developer
> Jerry Cheung

**Comment by JerryLoveZhiXin** [comment]
乱

**Comment by JerryLoveZhiXin** [comment]
或许可以帮您做新闻，
因为工时和志愿者展示我不知道流程。
UI是我最怕的东西:cry:
所以我尽量不参加:joy:
@zhangjingye03

**Comment by zhangjingye03** [comment]
猴啊 :smile: 
你先帮我看看后台的新闻编辑吧，找找别的类型的开源的html文本编辑器（有点网站发帖的感觉，可以弄粗字体啊设置颜色啊等等的，你有兴趣可以自己写一个，其实不难做）

**Comment by JerryLoveZhiXin** [comment]
能不能用学生会的那个wangedition :joy:
如果要自己写的话：
费时+UI的费脑！
我再找找有没有其他。
@zhangjingye03

**Comment by zhangjingye03** [comment]
不怎么伤脑啊，不就两个框，一个html代码，一个预览，上面有排按钮用来加粗什么的。。。
粗略看了下那个wangEditor，写的有点烂，代码不是很规范
用的话还是找些成熟的，比如去github[搜](https://github.com/search?l=JavaScript&q=rich+text+editor&ref=searchresults&type=Repositories&utf8=%E2%9C%93)，里面找JavaScript的；其中收藏数多的，一般就是大众所认可的

**Comment by JerryLoveZhiXin** [comment]
好好好
我去找找度娘和gayhub。
没去学js:joy:

**Comment by JerryLoveZhiXin** [comment]
@zhangjingye03

请学长预览一下此编辑器是否可用。

https://github.com/SmallOysterStudio/KindEditor

谢谢合作！

Jerry Cheung

**Comment by zhangjingye03** [comment]
不要带有php的

**Comment by JerryLoveZhiXin** [comment]
哦。

我貌似找到一个，但好像没有预览功能。我中午去看看。
