### ISSUE TITLE
老是出现请从正确途径进入？

### ISSUE THREAD

**Issue by kongoldwant** [zhxtw/qingzhi#17]
数据库文件`datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP   貌似这在mysql5.6版本下导入会错误，改成`datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP   就好了
  那个我这个后台老是登陆的时候说“请从正确的途径进入”我将isloggedin.php 里的地址修改成了自己的地址还是这个老是提示，后来我干脆把这个删了===这之后每次登陆进后台只能实现审核功能，点地点时段管理，修改密码都不行，弹出session过期，请重新登陆，谢谢你！

**Comment by SmallOyster** [comment]
# 关于“正确途径”的问题

**这是源于服务器的安全代码。**

## 解决方法

**▲打开isLoggedIn.php
▲将Line6~Line14代码删除
▲保存即可。**

# 关于功能的问题

**部分功能还没开发完……
前台只有报名/查询录取/反馈
后台只有审核/修改密码
敬请耐心等待我们的作品哦~**

# 关于SQL问题

**字段类型由于版本不同，
类型也不同
时间戳的类型为timestamp
更改即可**

## LAST

希望我的回复能给您带来方便~

> ZHXTW Website Assist Developer
> Jerry Cheung

**Comment by kongoldwant** [comment]
谢谢你，太专业了你^_^，那请问我登陆进去 点修改密码 他立即就弹出session已过期，hh，再一次谢谢你！

**Comment by SmallOyster** [comment]
请问还有什么问题吗？
嗯……
我能不能多问一句:
学长你高几？
初二学弟求勾搭hhh

> ZHXTW Website Assist Developer
> Jerry Cheung

**Comment by kongoldwant** [comment]
%>_<%学长都快上大学了。。。你们太666666了，别的问题就是我登陆进去 点修改密码 他立即就弹出session已过期

**Comment by SmallOyster** [comment]
额(⊙o⊙)…
这个问题我得去看看代码……
因为我没开电脑不好意思哈
周末帮您看看可以吗？

> ZHXTW Website Assist Developer
>     Jerry Cheung

**Comment by zhangjingye03** [comment]
访问的页面后面有跟`?token=................;`么？
或者页面上的链接有被自动加上`?token=................;`么？

实在不行删去`isLoggedIn.php`第三行的`||@!$_GET['token']`

**Comment by kongoldwant** [comment]
有的，去掉第三行的||@!$_GET['token']  就可以了，发现了一个问题，点击后台地点管理时，总是出现post的信息不完整，请重试。   还有删除按钮好像并没有什么用处

**Comment by SmallOyster** [comment]
@kongoldwant 
额不好意思……
那个功能还没完全开发完毕
敬请谅解和期待哦~

> ZHXTW Website Assist Developer
>     Jerry Cheung

**Comment by kongoldwant** [comment]
期待^_^，谢谢你，学长加油哦

**Comment by SmallOyster** [comment]
@kongoldwant 
我才初二，哪是学长……

> ZHXTW Website Assist Developer
>     Jerry Cheung
