### ISSUE TITLE
人生大事 之 人际交往

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#19]
@zhangjingye03 学长请问你有自拍照吗？
@NickelNi 请问学长的尊姓大名？高几哈？我想去勾搭~hhh

**Comment by zhangjingye03** [comment]
有也不是随便放在[全球最大的同性交友网站上](https://github.com)的 :joy:
那个家伙是个学霸+懒鬼，不写代码跑去玩高数，现数学建模社社长

**Comment by SmallOyster** [comment]
@zhangjingye03 微信发给我hhh。那他不写代码还拉他干嘛……

**Comment by zhangjingye03** [comment]
象征意义地
另，我不喜欢自拍

**Comment by SmallOyster** [comment]
有你人样的总有吧

**Comment by SmallOyster** [comment]
不好意思……又reopen
有你人样子的总有吧？黄bz说有。但他那儿没有

**Comment by nya-keru** [comment]
象徵的な?
2016年3月7日 21:13于 张靖业 notifications@github.com写道：象征意义地
另，我不喜欢自拍

**Comment by SmallOyster** [comment]
@NickelNi 啥意思
