### ISSUE TITLE
登记失败

### ISSUE THREAD

**Issue by kongoldwant** [zhxtw/qingzhi#20]
学长，你好，由于我们学校的学号是8位 于是我将signup.php中的
59行   if((!is_numeric($classno))||strlen($classno)!=4||substr($classno,0,2)<1||substr($classno,0,2)>17||substr($classno,2,2)<1||substr($classno,2,2)>60){
直接改成了 if((!is_numeric($classno))||strlen($classno)!=8
306行if(val.length!=4 || isNaN(val) || val.substr(0,2)<1 || val.substr(0,2)>17 || val.substr(2,2)<1 || val.substr(2,2)>60){
改成了if(val.length!=8
  可是每次点提交的时候都是弹出登记失败对话框，不能跳转到success.php   但在数据库中可以找到这条记录信息，谢谢O(∩_∩)O谢谢

**Comment by SmallOyster** [comment]
请修改数据库(qingzhi)中的signup表的classno字段长度为8。可通过“结构”功能修改。

**Comment by zhangjingye03** [comment]
- 可以先试试楼上的方法，修改字段长度
  `ALTER TABLE signup CHANGE classno classno VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;`
- 在`signup.php`的112行前加一句
  `echo("SELECT * FROM signup WHERE loc_name='{$loc_name}' and classno='{$classno}' and name='{$name}'");`
  将122行改成`diecho("登记失败\\n\\n请与我们联系。",0);` （禁用自动跳转）
  然后把页面上回显出来的sql查询语句复制到mysql中执行，麻烦把返回结果贴出来
- P.S. 我才高二，真的有资格做学长嘛... :joy:

**Comment by JerryLoveZhiXin** [comment]
我也才初二……更小……
@zhangjingye03 你的照片啊啊啊

**Comment by kongoldwant** [comment]
直接把数据库里改成8😂就好了。
Ps:还是叫你学长比较好😂说出来会羞羞的，至少你在知识上是我学长😄，那个location.json等我回去发你

**Comment by SmallOyster** [comment]
@kongoldwant
发什么啊？
要把你的location.json发给我们吗？
热烈欢迎哦！
只不过麻烦提交代码
请开一个pull request。
谢谢！

**Comment by kongoldwant** [comment]
是的呢，么么哒，学长猴赛雷！9.30下课回去发给你😂

**Comment by SmallOyster** [comment]
多谢学长！
欢迎一起努力哦！
