### ISSUE TITLE
location id 不存在

### ISSUE THREAD

**Issue by kongoldwant** [zhxtw/qingzhi#21]
由于无法使用后台的地点管理，我直接修改location.json 但是修改之后缩略图还是原来的，只有点击 报名 弹出来的模态框 图片是我自己设置的，这个弹粗来的模态框 会多显示
disabled    0
whydisabled 
image   /img/yly.jpg
点击报名之后显示 location id 不合法
![qq 20160309170738](https://cloud.githubusercontent.com/assets/17177570/13630276/7ad4fdf8-e619-11e5-83e9-5949ba448cb3.png)

**Comment by SmallOyster** [comment]
额(⊙o⊙)…
不好意思这个我不大懂……
回去研究研究，或者等张大大
(不是我，虽然我也姓张……)

**Comment by zhangjingye03** [comment]
> 会多显示
> disabled 0
> whydisabled 
> image /img/yly.jpg
> 缩略图还是原来的

这是一些bug，稍后我修复它

> 显示 location id 不合法

（可能的修复方案）如果在`location.json`中id是从0的话不能通过`location.php`中的`$loc_id<1`判断
能麻烦把`location.json`贴出来么？这样我好诊断一下 :smile: 

> 关于模态框中图片加载不出来的问题

我这里没有出现，能否检查下`/img/yly.jpg`是否存在呢

**Comment by JerryLoveZhiXin** [comment]
图片！人脸！
@zhangjingye03

**Comment by JerryLoveZhiXin** [comment]
图片！人脸照啊！

**Comment by JerryLoveZhiXin** [comment]
图片啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！
