### ISSUE TITLE
location.json

### ISSUE THREAD

**Issue by kongoldwant** [zhxtw/qingzhi#22]
{
    "loc":[
        {   "id":"1",
            "disabled":"1",
            "whydisabled":"由于上学期报名人数太多，未能安排完，故<span style='color:red'><b>这学期不进行报名</b></span>，上学期没有安排到的会在这学期继续安排。",
            "image":"/img/eryuan.jpg",
            "color":"info",
            "name":"市二院导医",
            "minintro":"周边环境优美，馆内凉爽舒适<s>，只是熊孩子有点难管</s>",
            "area":"天河区",
            "addr":"广州市天河区珠江东路4号",
            "traffic":"34路/34W路;35路/35W路;53路/53W路;59路/59W路(北行);59路/59W路(南行);76路/76W路;604",
            "works":["整理书籍","维持图书馆内秩序"],
            "times":["周六上午10点到12点30分","周六下午2点30分到5点","周日上午10点到12点30分","周日下午2点30分到5点"],
            "addrE":"http://f.amap.com/0CA18WX",
            "comm":["①图书馆志愿服务条是当天值日的组长领取且发给各位同学的，所以领完志愿服务条再走哦","②穿着执信校服","③要提前十分钟就在指定地点集中和组长签到。","④同学们要在广州新图书馆西门集合。","⑤如果有特殊情况不能前去服务点的，要自行找替换的同学并告诉本班爱心委员，不然请假、缺席（不包括替换）超过2次的同学会被取消在此志愿点服务的机会"]
        },
        {
            "id":"2",
            "disabled":"0",
            "whydisabled":"",
            "image":"/img/yly.jpg",
            "color":"danger",
            "name":"“青春伴夕阳”老人服务团活动之敬老院",
            "minintro":"敬老院",
            "area":"鼓楼区",
            "addr":"襄王南路",
            "traffic":"乘坐 地铁1号线农讲所站A出口处；乘坐3路 35路 65路 91路 101路 104路 106路 125路 183路 215长线 215路 236路 541路 B8路 广12路 21路 在中山图书馆站或文明路总站下车",
            "works":["帮助老人们"],
            "times":["周六上午9点到12点","周六下午2点到5点","周日上午9点到12点","周日下午2点到5点"],
            "addrE":"",
            "comm":["佩戴工作证","要提前十分钟就在指定地点集中和组长签到。","如果有特殊情况不能前去服务点的，要自行找替换的同学并告诉接口人，不然请假、缺席（不包括替换）超过2次的同学会被取消在此志愿点服务的机会"]
        },
        {
            "id":"3",
            "disabled":"0",
            "whydisabled":"",
            "image":"/img/xiaoxue.jpg",
            "color":"success",
            "name":"小学行",
            "minintro":"喜欢小朋友？！快来和他们玩耍？",
            "area":"鼓楼区",
            "addr":"黄河北路100号",
            "traffic":"95W路（工程学院中心校区方向）；64路/64W路（民馨园方向）；603路（西苑人家方向）",
            "works":["给小朋友讲课","和小朋友们玩耍"],
            "times":["周六下午3点到5点"],
            "addrE":"",
            "comm":["①记得多和小朋友们交流","②佩戴工作证啦","③提前十分钟就在指定地点集中和组长签到","④如果有特殊情况不能前去服务点的，要自行找替换的同学并告诉本班爱心委员，不然请假、缺席（不包括替换）超过2次的同学会被取消在此志愿点服务的机会"]
        },

```
]
```

}

**Comment by SmallOyster** [comment]
不好意思啊这个我也不大懂……
请耐心等待张大大的回复。
谢谢支持和配合！

**Comment by zhangjingye03** [comment]
第85行多了一个逗号

**Comment by kongoldwant** [comment]
学长火眼金睛，厉害，期待修复多显示的bug。^_^

**Comment by SmallOyster** [comment]
## hhh他可是学长大大！

@kongoldwant

## ……我还要你的照片……今天中午又找不到你

@zhangjingye03

**Comment by zhangjingye03** [comment]
@kongoldwant  昨晚已修复，请merge最新的代码

**Comment by SmallOyster** [comment]
@zhangjingye03
额那貌似是fork……
pull request才是merge……

**Comment by kongoldwant** [comment]
什么书merge？为啥看不到我开的帖子了？

**Comment by SmallOyster** [comment]
我们已经close了。
merge=合并(用于pull request)
fork=复制(用于复制到自己的账号)
如果有新的代码
可以点击项目右上角
“fork”按钮
以复制到自己的仓库

**Comment by kongoldwant** [comment]
666，涨姿势了

**Comment by SmallOyster** [comment]
只要你英语好就可以了/哈哈😄
我就是学不好英语，
天天搞错……
