### ISSUE TITLE
success.php中没有过滤掉json中无用信息

### ISSUE THREAD

**Issue by zhangjingye03** [zhxtw/qingzhi#25]
![bug](http://ww4.sinaimg.cn/large/5186ea03jw1f1u8xdglwaj20u01hctkb.jpg)
如图

由于json以后可能还会进行添加其他，因此修复时会在th()函数做点手脚

**Comment by SmallOyster** [comment]
哇学长为啥你的安卓手机可以浏览php！
你在手机是怎么做到的？
装什么服务器，代码编辑器？

**Comment by zhangjingye03** [comment]
- 浏览器一般都可以浏览php
- 这是我的电脑页面
- 安卓手机(4.4+)可以强行装`kali-linux`，然后安装`apache`、`nginx`、`php`等

**Comment by SmallOyster** [comment]
那为啥网址是100.100.100.254？
普通浏览器是能浏览，但不能加载php。

**Comment by zhangjingye03** [comment]
## 100.100.100.254是我的电脑的ip

根据[RFC6598](https://tools.ietf.org/html/rfc6598)的规定，2012年后`100.64.0.0/10`被划分为内网ip

贴个图给你

![img](http://ww2.sinaimg.cn/bmiddle/5186ea03gw1f1ucfbttbdj20ag0cdgn4.jpg)

**Comment by SmallOyster** [comment]
什么鬼你电脑连得是什么网络……
还要是win8的

**Comment by zhangjingye03** [comment]
我家的网络啊，ip想改啥就改啥，只要在
- 10.0.0.0/8
- 172.16.0.0/12
- 100.64.0.0/10
- 192.168.0.0/16

这些中挑一个就好了啊

**Comment by SmallOyster** [comment]
是改WiFi还是改电脑IP？
而且哦举个例子
我家电脑是192.168.73.250
但我用手机输入192.168.73.250却啥都没有……

**Comment by zhangjingye03** [comment]
首先，你要确保你的手机和电脑在同一网段
其次，你的电脑要开放运行有`apache`等web server的80号端口

**Comment by SmallOyster** [comment]
好吧

**Comment by SmallOyster** [comment]
那你的手机用的是什么浏览器？
能不能直接看源代码

**Comment by zhangjingye03** [comment]
Chrome，源码肯定看不了，要不然直接访问to_sql.php直接把数据库密码显示出来？

**Comment by SmallOyster** [comment]
额我是指直接在手机看网页源代码……不是php代码

**Comment by zhangjingye03** [comment]
Chrome可以，在网址前加view-source:即可

**Comment by SmallOyster** [comment]
那我还是用回我的Android FireFox吧
这个可以直接按按钮之后直接看。
