### ISSUE TITLE
人生大计 之 开发计划

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#27]
根据学长大大(项目主管 @zhangjingye03)

铁一般沉重的指令:joy:

来定一下我自己的计划:smile:
- [x] First.~~后台意见反馈管理~~ **已使用pdo，UI有待优化**
- [ ] Second.后台新闻发布/管理
- [x] Third.~~前台新闻展示~~ **已使用pdo**

总体希望期中考之前做完

分项来说计划时间太难了:joy:

**Comment by JerryLoveZhiXin** [comment]
@zhangjingye03 此沙发只作为提醒 猪冠大大 留意:joy:
