### ISSUE TITLE
Tips of Upload Codes

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#29]
@zhangjingye03
此贴仅为小小提醒。
有些微小的bug(如:文字上的提醒，小功能bug)
我就测试之后直接上传到github，
而不和你说声啦:joy:
所以麻烦您上传代码到FTP时，
下载一份在github最新的代码上传。
请放心这些微小的bug我会经过测试的。
谢谢！
## 

因为我看到我上传的代码没上传，
而你的上传了。

**Comment by zhangjingye03** [comment]
我是这么开发的：
本地测试一个文件夹，git的代码一个文件夹
每次都是准备写代码的时候git fetch一下，把变动的文件拷到本地测试目录；开发后把本地的新文件复制到git目录再git commit；上次因为我已经差不多弄完了才没有fetch而是直接commit了，顺便复制到服务器，导致没看到你最新的代码；下次更新的时候我会注意的

另:网站版本不是每次commit都去更新，因为这样太烦了(不要理页面下面的代码版本，它只会去api.github.con获取最新的，有时间我会加个网站现存版本上去 :joy:)

**Comment by SmallOyster** [comment]
@zhangjingye03
小的bug我会直接在github修改。
大的(很严重的)bug/新增功能:
我会先issues或者pull。
我知道肯定不会commits就上传一次，
那会晕死的:joy:
谢谢学长配合哈哈哈。
小心注意哈哈哈~
