### ISSUE TITLE
增加一个报名的选项

### ISSUE THREAD

**Issue by kongoldwant** [zhxtw/qingzhi#30]
学长，你好请问一下，如果想在signup.php里面加一个你对志愿者的看法这一个文字填写框，在数据库里添加一个字段，然后再signup.php里加入 37行左右if($_POST['name']&&$_POST['classno']&&/_$_POST['mobile']&&_/$_POST['verify_code']){
        $name=htmlspecialchars($_POST['name']);
        $classno=$_POST['classno'];
        $mobile=$_POST['mobile'];
        $jingli=$_POST['jingli'];    这样数据库里好像没有，求教该怎么写

**Comment by SmallOyster** [comment]
请问能否详细说明“数据库没有”的意思？
另外，if语句里面多了2个“/”符号。

**Comment by zhangjingye03** [comment]
后面还需要加入插入数据库的语句

在_最新_的代码版本中，将107~110行改成

```
$result = PDOQuery($dbcon, "INSERT INTO signup ".
                            "SET name = ?, mobile = ?, classno = ?, tworone = ?, loc_name = ?, times = ?, ip = ?, email = ?, jingli = ?",
                            [ $name , $mobile , $classno , $tworone , $loc_name , $times , $ip , $email , $jingli ] ,
                            [PDO::PARAM_STR,PDO::PARAM_STR,PDO::PARAM_STR,PDO::PARAM_STR,PDO::PARAM_STR,PDO::PARAM_STR,PDO::PARAM_STR,PDO::PARAM_STR,PDO::PARAM_STR]);
```

**Comment by kongoldwant** [comment]
恩 谢谢，这个我仿造你的做起来了，但是后台不知道怎么搞
![qq 20160412113651](https://cloud.githubusercontent.com/assets/17177570/14449127/75516792-00a2-11e6-8db7-b60e506ac6fa.jpg)   多了一列 这一列是数据表里的go  还是fromwap  请教一下该怎么删除，谢谢

**Comment by kongoldwant** [comment]
是直接把数据表里signup中的fromwap删除吗

**Comment by SmallOyster** [comment]
要去tableutils.js，
56行加上<th>表头内容</th>

@zhangjingye03 是否正解？

**Comment by SmallOyster** [comment]
要加上 th 内容 /th
(不造为啥输入标签后就不见了)
(th要加标签)

**Comment by kongoldwant** [comment]
那这个数据表里的classno  这个字段 在后台好像只显示前两位 我去掉manage.php 里的这个else if(j==="classno"){
                        append+="<td>"+got[i][j].substr(0,2)+"</td>";
                    }else{
                        append+="<td>"+got[i][j]+"</td>"   貌似不行额

**Comment by SmallOyster** [comment]
嗯。是要把substr(0,2)改成substr(0,4(或者其他位数))

所以这段嘛~应该别删除哦~

**Comment by kongoldwant** [comment]
谢谢，但我改成了10还是显示前两位

**Comment by SmallOyster** [comment]
麻烦亲检查一下数据库classno的结构。
我们当初只设定了2位。所以会这样。
麻烦亲在SQL里改一下哦~

**Comment by kongoldwant** [comment]
不不不，比如数据库里classno显示的学号是14083832   但后台管理里显示的就是14呢

**Comment by SmallOyster** [comment]
请问亲改了substr/SQL数据表显示的数据正确吗？

**Comment by kongoldwant** [comment]
感谢大神们的相助，已解决啦

**Comment by SmallOyster** [comment]
本问题已解决，于2016-04-13 10:59在课上关闭。
:joy:我在上语文课呢。

**Comment by zhangjingye03** [comment]
真当语文老师不上Github :joy:

**Comment by SmallOyster** [comment]
……我相信她没那么腻害。
快接我电话啊！
