### ISSUE TITLE
学长  那个志愿者查询的页面想把学号替换成手机号

### ISSUE THREAD

**Issue by kongoldwant** [zhxtw/qingzhi#31]
学长  那个志愿者查询的页面想把学号替换成手机号  我把query.php  
里的classno批量替换成成mobile，点查询按钮没反应

**Comment by zhangjingye03** [comment]
检查下checkSign3.js里头有没有改相关内容呢？

**Comment by kongoldwant** [comment]
都把classno改成mobile了   现在点立即查询没反应
