### ISSUE TITLE
addToken是如何获取Token值的？

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#32]
addToken是如何获取Token值的？
前面判断路径都懂了。
就是怎样获取
存在session的Token的值？

**Comment by zhangjingye03** [comment]
直接从访问网页的地址获取

最初token由登录成功后服务器返回

**Comment by SmallOyster** [comment]
不大懂…
因为看到你的导航链接是没有
?token=tokentokentoem;
这样的。
所以还是不懂你怎样获取到的
哈哈哈哈

**Comment by SmallOyster** [comment]
哦我懂了。
是不是这样：
登陆成功后就到index.php?token=dsdss;
然后加载addToken.js
获取网址的Token
然后在其他页面使用
是不是这样？
但js是怎样存住数据的？

**Comment by zhangjingye03** [comment]
1. 登录成功后跳转到manage.php?token=................;
2. 不需要存数据，因为理想状态下已经把所有a和form上的链接加了token，等访问这些页面时又会给其他页面链接加token.....以此循环

**Comment by SmallOyster** [comment]
第二部步不大明白 :joy:
不管了反正我照用就是了。
新闻还有操作接口和编辑器接口。
其实我应该做
你那个志愿者展示吧？
工时统计貌似要
等你想出来大概思路才好。

**Comment by SmallOyster** [comment]
还有我的一大锅注释
我正等着 :joy:
其实也不算急 :smile:
