### ISSUE TITLE
filter.php的那几个json怎样处理

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#34]
filter.php的那几个json怎样传给tableutils？

或者说是怎样处理？tableutils_filter.php

貌似看不到有Ajax啊。

@zhangjingye03

**Comment by zhangjingye03** [comment]
js的全局变量，然后再include到另一个php里

**Comment by SmallOyster** [comment]
哦……

那是在哪里选择我要过滤的条件？

会定义但不会用……

**Comment by zhangjingye03** [comment]
在每个单独的页面的onload事件里

比如

```
$(function(){
    mkfilters(['per','asc','loc','cls','xls']);
};
```

**Comment by SmallOyster** [comment]
哦~懂了

就是onload里面是filter的id。

但那个onclick的函数里面是什么意思

那个函数要怎么搞呢？

@zhangjingye03

**Comment by SmallOyster** [comment]
哦我懂了

onclick的事件的那个变量

会传到tableutils.js的req里的getRes

但是我不知道他那个onclick函数

的变量值是怎样传进去的……

可能我不大会JS吧。
