### ISSUE TITLE
求自动分配的原理

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#38]
求自动分配的原理？

**Comment by zhangjingye03** [comment]
见https://github.com/zhxtw/qingzhi/blob/master/admin/assign.php
里面有一小段注释你先看看吧，时隔太久我也有点忘了😂

**Comment by SmallOyster** [comment]
@zhangjingye03

你那注释实在……恶心 :cry:

表示看不懂……哈哈哈

**Comment by zhangjingye03** [comment]
我只能解释到这个水平了.........我觉得写的已经比较详细了啊

> /*
					日期计算
					1. 以settings.json中的起始和结束日期为基准，跳过disabledDates中的日期区间，跳过所有不属于此时段的days
					2. 让dtp1自动选择好起始日期后自动查询服务器该日期分配的人数，如果为0则可自动分配，如果不为0则查询下星期，直到结束后提示该学期已满
					3. 一次分配多组原理同上
					4. 为重复使用，分配完后推荐clear下dtp
					XXX：此做法有缺点，如果此时另一个人也登录分配，可能会产生爆人数等后果
				*/

**Comment by SmallOyster** [comment]
@zhangjingye03 
哈哈哈😂没事啦我去研究一下吧。我只是想不通你这个不用随机吗？

**Comment by zhangjingye03** [comment]
先到先得嘛，无可非议
