### ISSUE TITLE
session已过期怎么办?

### ISSUE THREAD

**Issue by rs-v** [zhxtw/qingzhi#39]

**Comment by SmallOyster** [comment]
请问你是指哪里的session……后台登录？

**Comment by rs-v** [comment]
后台登录

**Comment by SmallOyster** [comment]
过期的话，就只能重新登录吧。

**Comment by rs-v** [comment]
可是刚登陆就这样

**Comment by SmallOyster** [comment]
先检查一下是否启用了session，然后看一下get的参数里有没有token参数。

$_SESSION['adminname']
$_SESSION['logged']
$_SESSION['token']
$_GET['token']

逐个检查是否存在。

**Comment by rs-v** [comment]
都有

**Comment by rs-v** [comment]
if($_GET['token']!=$_SESSION['token'] && $_GET['token']!=$_SESSION['token'].";" && ($_GET['token']).";"!=$_SESSION['token']){
		session_destroy();

**Comment by rs-v** [comment]
你们是不是还没做完一些页面?

**Comment by SmallOyster** [comment]
是的，因为这个项目已经弃用了。

**Comment by rs-v** [comment]
难道有了替代品?

**Comment by SmallOyster** [comment]
其他原因，不方便透露，抱歉！

**Comment by rs-v** [comment]
好像不太支持php7

**Comment by rs-v** [comment]
js要求验证码4位而验证码却是5位

**Comment by SmallOyster** [comment]
抱歉了，因为弃用，所以也没有做更新维护。项目编写当年好像是没有PHP7的，验证码问题烦请您自己改一下吧~

**Comment by SmallOyster** [comment]
诶等等，你说的验证码问题出现在哪里？

**Comment by rs-v** [comment]
js\checksign.js    第55行

**Comment by rs-v** [comment]
前辈您现在工作了
   ##    我还是高二苦逼党

**Comment by rs-v** [comment]
学校连上了8天

**Comment by SmallOyster** [comment]
啊我也是高二的啊。

你还在执信青志？

**Comment by rs-v** [comment]
> 
> 
> 啊我也是高二的啊。
> 
> 你还在执信青志？
no

**Comment by SmallOyster** [comment]
我初中执信，高中不在了。

你的no是指你不在青志吗:joy:

**Comment by rs-v** [comment]
咱们还是在gitter聊吧
[Gitter](https://gitter.im/flfot/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
