### ISSUE TITLE
请问query.php的动画到底是咋样搞的？

### ISSUE THREAD

**Issue by SmallOyster** [zhxtw/qingzhi#9]
## query.php的modal动画框

我知道怎样搞但是不知道如何自动打开……
就是点击按钮后执行一段代码而后弹出modal
我看到query.php里是用checksign3.js，
我也试着调用了但却不行……
按钮的全部代码和编辑框的id/name我也对应修改了。
还是不行……
求解！谢谢！
## 我的设想

按钮点击后执行php代码(判断一些东西)，
如果判断错误就自动弹出modal，内容是什么什么的。

**Comment by SmallOyster** [comment]
## **补述现况**

看到query.php的modal内容是<p id='msg'>那我可不可以改成<?php echo $msg; ?>呢

## **目前最大的问题**

_**如何令它自动弹出来……**_

**Comment by JerryLoveZhiXin** [comment]
@zhangjingye03  学长求助

**Comment by zhangjingye03** [comment]
弹出来可以用$('#myModal').modal('show');，或者参考我写的checkSign.js里头的alt('xxx');函数
(checkSign3.js里面追加了一些东西比如说验证码是否计算完成等等)

这里不太推荐用php直接嵌套在js脚本里，可能会引发一些问题，比如说echo的东西如果有引号js就挂，或者echo以后给出header会报错.....
嵌套在页面里还可以，但如果多输出了个</div>之类的东西页面也会挂掉
最好的方法还是ajax

对了把你现在的代码贴出来我看看

**Comment by JerryLoveZhiXin** [comment]
哦……
我是指js嵌在php里
<?php if(){
echo “test”;
?>
<script>
alert(“test”);
</script>
<?php } ?>
测试代码 源代码等等上传。
Ajax真搞不定
alt或者show那个函数要怎么搞？
嵌在我刚刚写的代码的哪个位置？

**Comment by JerryLoveZhiXin** [comment]
哎呀script的代码显示不出来……
等中午再上传吧。
我的意思就是把script嵌在if的括号里

**Comment by SmallOyster** [comment]
[点击看源码](https://github.com/SmallOysterStudio/qingzhi/blob/master/admin/toModifyInfo.php)
我看了JS和CSS路径都没错，嗯只是我在github上传的时候不会新建目录……
我测试的是身份证号验证，其他都没搞。
身份证填错的话他应该会弹出modal，但居然不行弹不出来！
所以麻烦学长帮我看看应该怎样修改。谢谢。
麻烦给出修改后的源代码，嘻嘻~
@zhangjingye03

**Comment by SmallOyster** [comment]
附上我刚刚回复的意思的代码
<?php if(){
echo “test”;
?>
`<script>`
alert("1");
`</script>`
<?php } ?>

**Comment by zhangjingye03** [comment]
`<script>
show('<?php echo("xxx"); ?>');
</script>`

**Comment by SmallOyster** [comment]
哦谢谢学长，到时候试试。
那是直接把这个语句嵌在php里吗？
应该可以吧？

**Comment by SmallOyster** [comment]
就是指
<?php
if()
{?>
script show('<?php echo $msg; ?>');
<?php } ?>
show一定要先用双引号再写php语句吗
}

**Comment by zhangjingye03** [comment]
呃，不带这么用的，php标签不能断点执行
可以这样
`<?php 
$msg='xxx';
?>`
``
`< script>
a='<?php echo($msg); ?>';
</script>`
假设$msg内容为 呵呵
那么浏览器收到的script片段就是
a='呵呵';
你可以理解为，httpd服务在特定后缀文件里(如.php)，碰到<?标签就会直接扔给php处理，直到?>结束；在这里面不能直接写html和js代码，因为php不能解释它。

**Comment by SmallOyster** [comment]
咦我试过是可以的喔。
找时间试试吧。
因为如果像你怎么说如何把js代码括住？

**Comment by SmallOyster** [comment]
额我意思是
先php，前面的花括号{
然后?>
写HTML代码
然后<?php } ?>
因为我之前的家庭OA就用过这样是可以的喔

**Comment by zhangjingye03** [comment]
呃，这我没试过，改天试试看
不过这样代码的可读性很低...

**Comment by SmallOyster** [comment]
嗯确实。。。。但如何判断，把他扩展捏？

**Comment by JerryLoveZhiXin** [comment]
括住

**Comment by SmallOyster** [comment]
哦想到了这样
<?php
if(){$msg=0000;}
if(){$msg=1111;}
echo “script show('<?php echo $msg; ?>'); script”;
?>
这样可以吧？
我故意把script写成这样的。

**Comment by zhangjingye03** [comment]
这样理论上是可以的

P.S.可以用`把代码括起来，这样不会无缘无故被吞

**Comment by SmallOyster** [comment]
哦。谢谢。但手机输入好麻烦……
中午试试

**Comment by SmallOyster** [comment]
@zhangjingye03 还是不行。
[查看最新源码](https://github.com/SmallOysterStudio/qingzhi/blob/master/admin/toModifyInfo.php)
已经把js/css路径改了。因为我不懂在github创建文件夹……
还是不行啊，就算用了alt和show都无法显示……

> P.S.我故意把sql连接关了，方便在图书馆测试hhh

**Comment by SmallOyster** [comment]
要不我使用artDialog吧。我给你看看效果。
哎呀图片上传不来，你可以去搜搜或者来这儿看看
[点击进入，然后选择数据统计/查看需报销金额](http://sosit.pe.hu/oa/member.php)
这是我自己做的，因为要给你看所以没搞用户。就点中间两个按钮就好了。

**Comment by SmallOyster** [comment]
那个边框有很多样式，也可以改颜色。我喜欢这个default，可以改颜色的。

**Comment by zhangjingye03** [comment]
问题还是出在115行
js对双引号内换行要求十分严格
之前你echo($strout)，因为整个程序上没有$strout，php给了个错误消息
![123](http://ww4.sinaimg.cn/large/5186ea03gw1f1jxwszw38j20q20cptc0.jpg)
换行了，js因此出错

**Comment by SmallOyster** [comment]
yeah!可以了！

**Comment by SmallOyster** [comment]
谢谢学长！我知道怎么搞了！
